### ISSUE TITLE
将已有字段类型改为 map 的瞬间，thriftls 异常崩溃，并且不会再重新启动

### ISSUE THREAD

**Issue by chengjianhua** [joyme123/thriftls-vscode#6]
![20241017225404_rec_](https://github.com/user-attachments/assets/2ec9fe94-68a4-4b8d-ae7e-3dd03f97b811)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x5b4d42]

goroutine 172 [running]:
github.com/joyme123/thrift-ls/format.MustFormatFieldType(0x0)
	/source/format/field.go:105 +0x22
github.com/joyme123/thrift-ls/format.MustFormatFieldType(0xc00101dd00)
	/source/format/field.go:116 +0xd1
github.com/joyme123/thrift-ls/lsp/symbols.FieldSymbol(0xc001326d10)
	/source/lsp/symbols/field.go:19 +0x85
github.com/joyme123/thrift-ls/lsp/symbols.StructSymbol(0xc001326e70)
	/source/lsp/symbols/struct_like.go:23 +0x188
github.com/joyme123/thrift-ls/lsp/symbols.DocumentSymbols({0x93b240?, 0xc000b80230?}, 0x4b?, {0xc000234730?, 0x8000?})
	/source/lsp/symbols/document.go:41 +0x329
github.com/joyme123/thrift-ls/lsp.(*Server).documentSymbol(0x8479e0?, {0x93b240, 0xc000b80230}, 0x0?)
	/source/lsp/symbols.go:19 +0xc5
github.com/joyme123/thrift-ls/lsp.(*Server).DocumentSymbol(0xc0000c6e20, {0x93b240, 0xc000b80230}, 0xc0004305e0)
	/source/lsp/server.go:143 +0xf2
go.lsp.dev/protocol.serverDispatch({0x93b240, 0xc000b80230}, {0x944c30, 0xc0000c6e20}, 0xc00032a3c0, {0x93b400, 0xc000df1700})
	/go/pkg/mod/github.com/joyme123/protocol@v0.12.1-0.20230807112304-26cf0ace806b/server.go:386 +0x8023
github.com/joyme123/thrift-ls/lsp.(*StreamServer).ServeStream.ServerHandler.func2({0x93b240, 0xc000b80230}, 0xc00032a3c0, {0x93b400, 0xc000df1700})
	/go/pkg/mod/github.com/joyme123/protocol@v0.12.1-0.20230807112304-26cf0ace806b/server.go:36 +0x7e
go.lsp.dev/protocol.Handlers.ReplyHandler.func1({0x93b240, 0xc000b80230}, 0xc000d0f8f0, {0x93b400, 0xc000df1700})
	/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:35 +0xc6
go.lsp.dev/protocol.Handlers.AsyncHandler.func2.2()
	/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:114 +0x76
created by go.lsp.dev/protocol.Handlers.AsyncHandler.func2 in goroutine 9
	/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:112 +0x165
[Error - 10:54:13 PM] Connection to server got closed. Server will not be restarted.
[Error - 10:54:13 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at LanguageClient.handleConnectionClosed (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at closeHandler (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at CallbackList.invoke (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at CallbackList.invoke (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at StreamMessageReader.fireClose (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at Pipe.<anonymous> (node:net:339:12)
[Error - 10:54:13 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at LanguageClient.handleConnectionClosed (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at closeHandler (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at CallbackList.invoke (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at CallbackList.invoke (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at StreamMessageReader.fireClose (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.7/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (node:events:531:35)
    at Socket.emit (node:domain:488:12)
    at Pipe.<anonymous> (node:net:339:12)

```

**Comment by joyme123** [comment]
@chengjianhua 感谢反馈，这个问题我会尽快看一下

**Comment by joyme123** [comment]
@chengjianhua 问题已修复，需要 Reload vscode 一下，thrift-language-server 会自动下载最新版本的 thriftls。

如果下载失败（可能是因为 github api 限流），可以尝试用 vpn 或者换一个网络试试

**Comment by chengjianhua** [comment]
> @chengjianhua 问题已修复，需要 Reload vscode 一下，thrift-language-server 会自动下载最新版本的 thriftls。
> 
> 如果下载失败（可能是因为 github api 限流），可以尝试用 vpn 或者换一个网络试试

给力，Bro。同学可以用用户名在飞书里找到我，同学的插件是目前最好用的版本~
