### ISSUE TITLE
插件启动失败，无法下载 Thrift Language Server

### ISSUE THREAD

**Issue by chengjianhua** [joyme123/thriftls-vscode#8]
```
2024-10-28 20:23:22.799 [error] Activating extension jiangpengfei.thrift-language-server failed due to an error:
2024-10-28 20:23:22.799 [error] Error: Failed to download https://github.com/joyme123/thrift-ls/releases/download/v0.2.5/thriftls-linux-amd64:
connect ETIMEDOUT 20.205.243.166:443
    at downloadFile (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.8/client/src/utils.ts:199:15)
    at downloadThriftLanguageServer (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.8/client/src/download.ts:213:5)
    at activate (/data00/home/chengjianhua/.vscode-server/extensions/jiangpengfei.thrift-language-server-1.0.8/client/src/extension.ts:75:24)
    at x0.n (file:///data00/home/chengjianhua/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/workbench/api/node/extensionHostProcess.js:114:4450)
    at x0.m (file:///data00/home/chengjianhua/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/workbench/api/node/extensionHostProcess.js:114:4413)
    at x0.l (file:///data00/home/chengjianhua/.vscode-server/cli/servers/Stable-384ff7382de624fb94dbaf6da11977bba1ecd427/server/out/vs/workbench/api/node/extensionHostProcess.js:114:3869)
```

**Comment by chengjianhua** [comment]
@joyme123

**Comment by chengjianhua** [comment]
我是在开发机下下载，可能网络不太好，但是没有办法指定代理来下载。

**Comment by chengjianhua** [comment]
https://code.visualstudio.com/docs/setup/network 通过设置 http.proxy 解决了……还是希望有更好的办法，例如允许填写一个内网托管的地址。

**Comment by joyme123** [comment]
> 例如允许填写一个内网托管的地址。

嗯。可以考虑引导用户手动下载，然后填本地路径就行。

**Comment by joyme123** [comment]
@chengjianhua v1.0.9 支持在插件设置里填入一个本地的 thriftls 二进制文件路径，这个二进制文件可以手动下载放在机器上的任何位置。设置了之后，就不会再通过网络下载了。

<img width="840" alt="image" src="https://github.com/user-attachments/assets/026ed31d-02d9-4b2b-a2b3-b7d5063b0c51">

**Comment by chengjianhua** [comment]
@joyme123 赞，高效！
